{% set name = "biokit" %}
{% set version = "1.0" %}
{% set git_url = "" %}
{% set git_rev = "main" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: https://github.com/MaizeMan-JxFU/biokit.git
  git_url: main

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - biokit

about:
  home: "https://github.com/MaizeMan-JxFU/biokit"